### ISSUE TITLE
Is 'broadcat' part of the API?

### ISSUE THREAD

**Issue by rsxdalv** [lucidrains/rotary-embedding-torch#17]
With the latest versions broadcat function is no longer available to import; however, projects like tortoise depend on this import. Should this import have been private, and not part of the public API?

**Comment by lucidrains** [comment]
@rsxdalv oh oops! no idea it was being used, and in such a high profile project!

in a later commit, i discovered `broadcast_tensors` and that function got reduced down to 3 loc

```python
from torch import broadcast_tensors

def broadcat(tensors, dim = -1):
    broadcasted_tensors = broadcast_tensors(*tensors)
    return torch.cat(broadcasted_tensors, dim = dim)
```

**Comment by rsxdalv** [comment]
Actually I discovered that it's being imported but not being used; I didn't realize this at first as I'm a downstream project from tortoise.

Thank you for the quick response.

**Comment by rsxdalv** [comment]
So, in the scope of _tortoise_ project, this issue can be closed.

**Comment by lucidrains** [comment]
@rsxdalv got it, yea, i brought it back just to save you the trouble

**Comment by rsxdalv** [comment]
Thank you, that will fix my project's installation!
