### ISSUE TITLE
xPOS embeddings during inference

### ISSUE THREAD

**Issue by VarunGumma** [lucidrains/rotary-embedding-torch#27]
Hi @lucidrains,

I see that while using RoPE during inference (cached keys), we have to use the `rotate_queries_with_cached_keys(q, k)` method, or manually add an `offset`. What would be the case for xPOS? I see that offset is required as per [torchscale](https://github.com/microsoft/torchscale/blob/main/torchscale/component/xpos_relative_position.py), but there is not scope for it in this implementation. Can you please take a look and fix it?

**Comment by lucidrains** [comment]
@VarunGumma hey Varun! yes you are right i didn't account for xpos in that function

do you want to see if 0.6.3 works?

**Comment by VarunGumma** [comment]
@lucidrains, thanks for the quick fix! I have not tested it, but as per my knowledge, that's how it should be. I have integrated your module into my [fairseq](https://github.com/VarunGumma/fairseq) repo which can help train RoPE-based transformer models.
