### ISSUE TITLE
Unused params if cache_if_possible=True when multiple rotary dimensions are used

### ISSUE THREAD

**Issue by lukasschmit** [lucidrains/rotary-embedding-torch#37]
If a model is trained in DDP in which multiple submodules have different rotary dimensions (e.g. a smaller auxiliary encoder), it seems the caching mechanism breaks such that the `freqs` will be used. This will lead to crashes in DDP due to unused params although I expect this also indicates broken caching logic if different hidden dims are used in the same architecture.

setting `cache_if_possible=False` is a workaround.

**Comment by lucidrains** [comment]
yeah, that seems like an edge case where caching should just be turned off
