### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'to'

### ISSUE THREAD

**Issue by yingzhao27** [lucidrains/rotary-embedding-torch#7]
When runing test case,  
AttributeError: 'NoneType' object has no attribute 'to'

**Comment by lucidrains** [comment]
can you show the full script you are running?

**Comment by yingzhao27** [comment]
> can you show the full script you are running?

hello, I just use the code you provide in ”Usage", that is:
`import torch
from rotary_embedding_torch import RotaryEmbedding

# instantiate the positional embedding in your transformer and pass to all your attention layers

rotary_emb = RotaryEmbedding(dim = 32)

# mock queries and keys - dimensions should end with (seq_len, feature dimension), and any number of preceding dimensions (batch, heads, etc)

q = torch.randn(1, 8, 1024, 64) # queries - (batch, heads, seq len, dimension of head)
k = torch.randn(1, 8, 1024, 64) # keys

# apply the rotations to your queries and keys after the heads have been split out, but prior to the dot product and subsequent softmax (attention)

q = rotary_emb.rotate_queries_or_keys(q)
k = rotary_emb.rotate_queries_or_keys(k)

# then do your attention with your queries (q) and keys (k) as usual`

**Comment by yingzhao27** [comment]
> > can you show the full script you are running?
> 
> hello, I just use the code you provide in ”Usage", that is: `import torch from rotary_embedding_torch import RotaryEmbedding
> 
> rotary_emb = RotaryEmbedding(dim = 32)
> 
> q = torch.randn(1, 8, 1024, 64) # queries - (batch, heads, seq len, dimension of head) k = torch.randn(1, 8, 1024, 64) # keys
> 
> q = rotary_emb.rotate_queries_or_keys(q) k = rotary_emb.rotate_queries_or_keys(k) print(q)

Now it's OK. Sorry to disturb.
