### ISSUE TITLE
Using with xpos causes NaNs after rotating Q, K

### ISSUE THREAD

**Issue by andersonbcdefg** [lucidrains/rotary-embedding-torch#8]
I discovered that after rotary_emb.rotate_queries_and_keys(Q, K), K now contains a very small fraction of NaNs, which then propagate through the rest of the transformer and result in a NaN loss. What could be causing this / how to address? Happy to provide code if it helps.

**Comment by lucidrains** [comment]
@andersonbcdefg ugh! i'm so embarrassed. thank you! https://github.com/lucidrains/rotary-embedding-torch/commit/2605ece8a6a08f5a1eceb8f56cf78ccd7670e1b5

**Comment by andersonbcdefg** [comment]
No, thank you for fixing so quickly and making this library available period! Normal people wouldn't be able to use xpos rotary embeddings properly if not for all your work :)
